spring:
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:test
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 469264102297-ubbir11toe7fn028givu85541hd85vto.apps.googleusercontent.com
            clientSecret: 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
            scope: profile, email
  jwt:
    key: SPRINGBOOTPROJECTJWTTOKENLOCALTESTSECRETKEY
    access-token-expiration-minutes: 30
    refresh-token-expiration-minutes: 420
